modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="hdu"
version="1.1.0-dev"
displayName="Dedrarion Underground"
authors="Haru (Hivens)"
description='''Part for Dedrarion. Lets explore caves!'''

[[dependencies.hdu]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.hdu]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.hdu]]
modId="dedrarion"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.hdu]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.hdu]]
modId="jeresources"
mandatory=false
versionRange="[1.4.0,)"
ordering="NONE"
side="BOTH"
